# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev_Deploy
    dependsOn: Prod_Deploy
    jobs:
      - job: Job1
        steps:
          - script: echo Dev Deploy!
            displayName: "Run a one-line script"

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: "Run a multi-line script"

      - job: Job2
        dependsOn: Job3
        steps:
          - script: echo Job2 from Dev Deploy -------------------------!
            displayName: "Run a one-line script"

      - job: Job3
        dependsOn:
          - Job1
          - Job4
        steps:
          - script: echo Job3 from Dev Deploy -------!
            displayName: "Run a one-line script"

      - job: Job4
        steps:
          - script: echo Job3 from Dev Deploy -------!
            displayName: "Run a one-line script"

  - stage: QA_Deploy
    dependsOn: Prod_Deploy
    jobs:
      - job: Job1
        steps:
          - script: echo QA Deploy Job1!
            displayName: "Run a one-line script QA Deploy"

      - job: Job2
        dependsOn: Job1
        steps:
          - script: echo Job2 from QA Deploy-------------------------!
            displayName: "Run a one-line script"

  - stage: Prod_Deploy
    jobs:
      - job: Job1
        steps:
          - script: echo Production Deploy Job1!
            displayName: "Run a one-line script Prod Deploy"
